runtime: nodejs22
service: backend
env: standard
instance_class: F1
vpc_access_connector:
  name: projects/tokyo-mind-458722-t5/locations/us-west1/connectors/wilddex-connector
automatic_scaling:
  max_instances: 1
  min_instances: 1